language: php

dist: trusty

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

install:
 - composer require satooshi/php-coveralls:~1.0@stable
 - composer update
 - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

before_script:
 - mkdir -p build/logs

script:
- php phpcs.phar -h
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
 - travis_retry php vendor/bin/coveralls
